Add check to ensure that the SOURCE_BRANCH argument is defined.

diff --git a/scripts/docker/Dockerfile b/scripts/docker/Dockerfile
--- a/scripts/docker/Dockerfile
+++ b/scripts/docker/Dockerfile
@@ -5,6 +5,13 @@ MAINTAINER John Halley Gotway <johnhg@ucar.edu>
 # This Dockerfile compiles MET from source during "docker build" step
 #
 ARG SOURCE_BRANCH
+RUN if [ "x${SOURCE_BRANCH}" = "x" ]; then \
+      echo "ERROR: SOURCE_BRANCH undefined! Rebuild with \"--build-arg SOURCE_BRANCH={branch name}\""; \
+      exit 1; \
+    else \
+      echo "Build Argument SOURCE_BRANCH=${SOURCE_BRANCH}"; \
+    fi
+
 ENV MET_GIT_NAME    ${SOURCE_BRANCH}
 ENV MET_GIT_URL     https://github.com/NCAR/MET
 ENV MET_DEVELOPMENT true
