Fix output typo to outputs and remove METbaseimage defaults from Dockerfile and change them to required arguments.

diff --git a/internal/scripts/docker/Dockerfile.copy b/internal/scripts/docker/Dockerfile.copy
--- a/internal/scripts/docker/Dockerfile.copy
+++ b/internal/scripts/docker/Dockerfile.copy
@@ -1,5 +1,8 @@
-ARG MET_BASE_REPO=met-base-unit-test
-ARG MET_BASE_TAG=13.0
+ARG MET_BASE_REPO
+ARG MET_BASE_TAG
+
+RUN test -n "$MET_BASE_REPO" || (echo "MET_BASE_REPO build-arg is required" >&2 && exit 1)
+RUN test -n "$MET_BASE_TAG" || (echo "MET_BASE_TAG build-arg is required" >&2 && exit 1)
 
 FROM dtcenter/${MET_BASE_REPO}:${MET_BASE_TAG}
 MAINTAINER John Halley Gotway <johnhg@ucar.edu>
