instead of failing if a diff is found in a unit test, run a job at the end that checks if any diff files were found and fails if so, ci-run-unit

diff --git a/.github/workflows/pr_unit_tests.yml b/.github/workflows/pr_unit_tests.yml
--- a/.github/workflows/pr_unit_tests.yml
+++ b/.github/workflows/pr_unit_tests.yml
@@ -256,3 +256,19 @@ jobs:
           name: logs
           path: ${{ runner.workspace }}/logs
           if-no-files-found: ignore
+
+  check_for_diffs:
+    name: Check if there were any differences
+    runs-on: ubuntu-latest
+    needs: [unit_tests1, unit_tests2c]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/download-artifact@v2
+        with:
+          name: diff
+          path: diff
+      - run: |
+          if [ "$(ls -A diff)" ]; then
+            echo "ERROR: Differences exist in the output"
+            exit 1
+          fi
